
site_name: prismscore Documentation
theme:
  name: material
  features:
    - navigation.instant
    - toc.follow
    - navigation.tabs
nav:
    - Home: 'index.md'
    - Documentation: 'details.md'
    - About:
      - 'About': 'about.md'
      - 'Command Certification': 'certification.pdf'
      - 'License': 'license.md'
      - 'Release Notes': 'release-notes.md'
repo_url: https://github.com/razvanazamfirei/prism-score