name: ci-cd

on: [push]

jobs:
  cd:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace:
          - lib1
          - lib2
          - service

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - id: analyze
        uses: rotorsoft/semrel-analyze@v1
        with:
          package: "@scope/${{ matrix.workspace }}"
          directory: "workspace/${{ matrix.workspace }}"
          
      - name: analysis
        run: |
          echo "last-tag: ${{ steps.analyze.outputs.last-tag }}"
          echo "next-tag: ${{ steps.analyze.outputs.next-tag }}"
          echo "next-version: ${{ steps.analyze.outputs.next-version }}"
          echo "${{ steps.analyze.outputs.change-log }}"
